# F1 Data Analysis Project

The Formula 1 Data Analysis project is a comprehensive exploration of the world of Formula 1 racing through the lens of data analytics. This project combines the power of SQL for data manipulation in addition to Deepnote and Tableau for data visualisation to provide insights into the thrilling world of Formula 1 racing from 1953-2020. This project aims to identify candidates for the greatest Formula 1 driver of all time.

## Key Components:

Data Collection and Preparation: The project begins by gathering extensive Formula 1 data, including race results, driver statistics, team information, and circuit details. This raw data is then cleaned and organised for analysis.

Database Design: A relational database is created using SQL to efficiently store and manage the Formula 1 data. This step includes defining tables, relationships, and constraints to ensure data integrity.

SQL Data Queries: SQL queries are crafted to extract meaningful insights from the database. This may involve calculating driver and team performance metrics, historical trend analysis, and identifying key patterns in the data.

Tableau Visualization: The SQL-derived insights are visualised using Tableau, a powerful data visualisation tool. Interactive dashboards and reports are designed to provide users with a user-friendly interface to explore the data.

Performance Analysis: Using SQL and Tableau, the project delves into various aspects of Formula 1 racing, such as driver performance across seasons, race track statistics, and the impact of rule changes.

Reporting and Presentation: The project concludes by creating comprehensive reports and presentations that summarise the findings, making it accessible to a wider audience.

## Benefits:

Gain a deeper understanding of Formula 1 racing from a data-driven perspective.

Enhance the overall Formula 1 fan experience by making complex data accessible and engaging.

This project offers a unique opportunity to combine the technical skills of SQL with the data visualisation capabilities of Deepnote and Tableau to unlock insights about one of the dynamic sports in the world.

## Project Links:

Tableau Dashboard

Github Repository

# EDA

We will begin by performing exploratory data analysis to understand the data structure, identify errors, outliers and anomalies, plus uncover patterns and relationships. 

## General Queries

Firstly, let's identify the most experienced driver:

In [121]:
df_2 = _deepnote_execute_sql('-- Find the driver who has competed in the most races\n\nSELECT \n    r.driverId, \n    COUNT(r.RaceId) AS race_count, \n    d.surname, \n    d.forename\nFROM \'results.csv\' r\nJOIN \'drivers.csv\' d ON r.driverId = d.driverId\nGROUP BY r.driverId, d.surname, d.forename\nORDER BY race_count DESC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_2

driverID  race_count      surname  forename
0           4         358       Alonso  Fernando
1           8         352    Raikkonen      Kimi
2          22         326  Barrichello    Rubens
3           1         310     Hamilton     Lewis
4          18         309       Button    Jenson
..        ...         ...          ...       ...
850       639           1      Milhoux     Andre
851       301           1       Morgan      Dave
852       545           1       Gamble      Fred
853       652           1    Whiteaway       Ted
854       683           1       Thorne    Leslie

[855 rows x 4 columns]

From this query, we can see that the driver who has participated in the most races is Fernando Alonso (358), followed by Kimi Raikonnen (352). Let's visualise the top 25 drivers with the most races:

In [2]:
DeepnoteChart(df_2, """{"layer":[{"layer":[{"mark":{"clip":true,"type":"bar","tooltip":true},"encoding":{"x":{"axis":{"title":"Race Count"},"sort":null,"type":"quantitative","field":"race_count","scale":{"type":"linear"},"format":{"type":"default","decimals":null},"aggregate":"sum","formatType":"numberFormatFromNumberType"},"y":{"axis":{"title":"Driver Name"},"sort":null,"type":"nominal","field":"surname","scale":{"type":"linear"}},"color":{"sort":null,"type":"quantitative","field":"race_count","scale":{"scheme":"goldgreen"},"aggregate":"sum"}}},{"mark":{"dx":3,"dy":0,"fill":"black","type":"text","align":"left","baseline":"middle"},"encoding":{"x":{"axis":{"title":"Race Count"},"sort":null,"type":"quantitative","field":"race_count","scale":{"type":"linear"},"format":{"type":"default","decimals":null},"aggregate":"sum","formatType":"numberFormatFromNumberType"},"y":{"axis":{"title":"Driver Name"},"sort":null,"type":"nominal","field":"surname","scale":{"type":"linear"}},"text":{"sort":null,"type":"quantitative","field":"race_count","aggregate":"sum"},"color":{"sort":null,"type":"quantitative","field":"race_count","scale":{"scheme":"goldgreen"},"aggregate":"sum"}}}]}],"title":"Most Races","config":{"legend":{}},"$schema":"https://vega.github.io/schema/vega-lite/v5.json","encoding":{}}""")

Now let's take a closer look at the stellar career of Fernando Alonso. 

In [3]:
df_3 = _deepnote_execute_sql('-- Investigating Alonso\'s career\n\nSELECT \n    r.RaceID,\n    r.driverID,\n    r.fastestLapTime,\n    r.fastestLapSpeed,\n    ra.circuitId,\n    ra.date,\n    c.name\nFROM \'results.csv\' r\nJOIN \'races.csv\' ra ON r.RaceId = ra.RaceID\nLEFT JOIN \'circuits.csv\' c ON ra.circuitId = c.circuitId\nWHERE r.driverId = \'4\' AND r.fastestLapSpeed <> 0\nORDER BY r.fastestLapTime ASC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_3

RaceID  driverID fastestLapTime  fastestLapSpeed  circuitId        date  \
0      1060         4        01:08.4          227.246         70  2021-07-04   
1      1084         4        01:08.5          226.739         70  2022-07-10   
2       997         4        01:08.6          226.399         70  2018-07-01   
3      1058         4        01:09.7          222.867         70  2021-06-27   
4       956         4        01:11.0          219.284         70  2016-07-03   
..      ...       ...            ...              ...        ...         ...   
307       3         4        01:54.4          171.413         17  2009-04-19   
308      86         4        01:56.1          216.252         13  2005-09-11   
309     337         4        01:58.2          191.706          3  2010-03-14   
310    1091         4        02:00.4          151.306         15  2022-10-02   
311     982         4        02:13.5          136.503         15  2017-09-17   

                               name  
0                     Red Bull Ring  
1                     Red Bull Ring  
2                     Red Bull Ring  
3                     Red Bull Ring  
4                     Red Bull Ring  
..                              ...  
307  Shanghai International Circuit  
308    Circuit de Spa-Francorchamps  
309   Bahrain International Circuit  
310       Marina Bay Street Circuit  
311       Marina Bay Street Circuit  

[312 rows x 7 columns]

Visualising Alonso's fastest laps at each circuit:

In [36]:
DeepnoteChart(df_3, """{"layer":[{"layer":[{"mark":{"clip":true,"type":"circle","tooltip":true},"encoding":{"x":{"axis":{"title":"Track Name"},"sort":null,"type":"nominal","field":"name","scale":{"type":"linear","zero":false}},"y":{"sort":null,"type":"nominal","field":"fastestLapTime","scale":{"type":"linear","zero":false}},"color":{"sort":null,"type":"nominal","field":"name","scale":{"scheme":"tableau10"}}}}]}],"title":"Alonso\\\\'s Fastest Laps By Track","config":{"legend":{"disable":true}},"$schema":"https://vega.github.io/schema/vega-lite/v5.json","encoding":{}}""")

Now we're going to explore the statistics for all drivers, ordered by fastest ever lap times across all circuits.

In [5]:
df_4 = _deepnote_execute_sql('-- See driver stats ordered by Fastest Lap Time\n\nSELECT \n    r.RaceID,\n    r.driverID,\n    d.forename,\n    d.surname, \n    r.fastestLapTime,\n    r.fastestLapSpeed,\n    ra.circuitId,\n    ra.date,\n    c.name\nFROM \'results.csv\' r\nJOIN \'races.csv\' ra ON r.RaceId = ra.RaceID\nJOIN \'drivers.csv\' d ON r.driverId = d.driverId\nLEFT JOIN \'circuits.csv\' c ON ra.circuitId = c.circuitId\nWHERE r.fastestLapSpeed <> 0\nORDER BY r.fastestLapTime ASC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_4

RaceID  driverID    forename     surname fastestLapTime  \
0       1046       847      George     Russell        00:55.4   
1       1046       822    Valtteri      Bottas        00:56.5   
2       1046       815      Sergio       Perez        00:56.7   
3       1046       841     Antonio  Giovinazzi        00:56.8   
4       1046        20   Sebastian      Vettel        00:56.9   
...      ...       ...         ...         ...            ...   
7374     957       836      Pascal    Wehrlein        02:48.8   
7375      45         3        Nico     Rosberg        02:50.9   
7376     871       813      Pastor   Maldonado        02:56.1   
7377      45        26       Scott       Speed        03:01.9   
7378      45        24  Vitantonio      Liuzzi        03:22.3   

      fastestLapSpeed  circuitId        date                           name  
0             230.214          3  2020-12-06  Bahrain International Circuit  
1             225.497          3  2020-12-06  Bahrain International Circuit  
2             224.599          3  2020-12-06  Bahrain International Circuit  
3             224.212          3  2020-12-06  Bahrain International Circuit  
4             224.141          3  2020-12-06  Bahrain International Circuit  
...               ...        ...         ...                            ...  
7374          125.634          9  2016-07-10            Silverstone Circuit  
7375          108.410         20  2007-07-22                    Nurburgring  
7376          143.116         13  2012-09-02   Circuit de Spa-Francorchamps  
7377          101.884         20  2007-07-22                    Nurburgring  
7378           91.610         20  2007-07-22                    Nurburgring  

[7379 rows x 9 columns]

The previous query shows some unusually fast lap times for RaceID 1046 (under 60 seconds), which was at Bahrain 2020. Let's investigate further by looking at the fastest laps for each race at Bahrain:

In [6]:
df_5 = _deepnote_execute_sql('-- What are the fastest lap times for Bahrain?\n\nWITH BahrainRaces AS (\n    SELECT\n        r.RaceID,\n        r.fastestLapTime,\n        ra.circuitId,\n        ra.date,\n        c.name,\n        ROW_NUMBER() OVER (PARTITION BY r.RaceID ORDER BY r.fastestLapTime ASC) as LapRank\n    FROM \'results.csv\' r\n    JOIN \'races.csv\' ra ON r.RaceId = ra.RaceID\n    LEFT JOIN \'circuits.csv\' c ON ra.circuitId = c.circuitId\n    WHERE r.fastestLapSpeed <> 0 AND c.name = \'Bahrain International Circuit\'\n),\nFastestLaps AS (\n    SELECT\n        RaceID,\n        fastestLapTime,\n        circuitId,\n        date,\n        name\n    FROM BahrainRaces\n    WHERE LapRank = 1\n)\nSELECT\n    RaceID,\n    fastestLapTime,\n    circuitId,\n    date,\n    name,\n    RANK() OVER (ORDER BY fastestLapTime ASC) as FastestLapRank\nFROM FastestLaps\nORDER BY FastestLapRank;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_5

RaceID fastestLapTime  circuitId        date  \
0     1046        00:55.4          3  2020-12-06   
1       92        01:30.2          3  2004-04-04   
2       73        01:31.4          3  2005-04-03   
3     1045        01:32.0          3  2020-11-29   
4     1052        01:32.0          3  2021-03-28   
5       53        01:32.4          3  2006-03-12   
6      971        01:32.7          3  2017-04-16   
7       20        01:33.1          3  2008-04-06   
8     1011        01:33.4          3  2019-03-31   
9      990        01:33.7          3  2018-04-08   
10      38        01:34.0          3  2007-04-15   
11     949        01:34.4          3  2016-04-03   
12    1074        01:34.5          3  2022-03-20   
13       4        01:34.5          3  2009-04-26   
14     863        01:36.3          3  2012-04-22   
15     929        01:36.3          3  2015-04-19   
16     883        01:36.9          3  2013-04-21   
17     902        01:37.0          3  2014-04-06   
18     337        01:58.2          3  2010-03-14   

                             name  FastestLapRank  
0   Bahrain International Circuit               1  
1   Bahrain International Circuit               2  
2   Bahrain International Circuit               3  
3   Bahrain International Circuit               4  
4   Bahrain International Circuit               4  
5   Bahrain International Circuit               6  
6   Bahrain International Circuit               7  
7   Bahrain International Circuit               8  
8   Bahrain International Circuit               9  
9   Bahrain International Circuit              10  
10  Bahrain International Circuit              11  
11  Bahrain International Circuit              12  
12  Bahrain International Circuit              13  
13  Bahrain International Circuit              13  
14  Bahrain International Circuit              15  
15  Bahrain International Circuit              15  
16  Bahrain International Circuit              17  
17  Bahrain International Circuit              18  
18  Bahrain International Circuit              19

In [7]:
DeepnoteChart(df_5, """{"layer":[{"layer":[{"mark":{"clip":true,"type":"trail","color":"#e45756","tooltip":true},"encoding":{"x":{"sort":null,"type":"quantitative","field":"FastestLapRank","scale":{"type":"linear","zero":false},"format":{"type":"default","decimals":null},"formatType":"numberFormatFromNumberType"},"y":{"sort":"ascending","type":"nominal","field":"fastestLapTime","scale":{"type":"linear","zero":false}}}},{"mark":{"size":100,"type":"point","opacity":0,"tooltip":true},"encoding":{"x":{"sort":null,"type":"quantitative","field":"FastestLapRank","scale":{"type":"linear","zero":false},"format":{"type":"default","decimals":null},"formatType":"numberFormatFromNumberType"},"y":{"sort":"ascending","type":"nominal","field":"fastestLapTime","scale":{"type":"linear","zero":false}}}}]}],"title":"Bahrain - Fastest Laps","config":{"legend":{}},"$schema":"https://vega.github.io/schema/vega-lite/v5.json","encoding":{}}""")

The results show that discounting RaceID 1046, the next fastest times are over 30 seconds slower, meaning we likely have an anomaly. Further investigation shows this race was a one time, reformatted race due to COVID. Therefore, it shall be discounted from this query to avoid skewing the results. Let's run the query without data from RaceID 1046:

In [8]:
df_6 = _deepnote_execute_sql('-- View driver stats ordered by Fastest Lap Time excluding RaceID 1046\n\nSELECT \n    r.RaceID,\n    r.driverID,\n    d.forename,\n    d.surname, \n    r.fastestLapTime,\n    r.fastestLapSpeed,\n    ra.circuitId,\n    ra.date,\n    c.name\nFROM \'results.csv\' r\nJOIN \'races.csv\' ra ON r.RaceId = ra.RaceID\nJOIN \'drivers.csv\' d ON r.driverId = d.driverId\nLEFT JOIN \'circuits.csv\' c ON ra.circuitId = c.circuitId\nWHERE r.fastestLapSpeed <> 0 AND r.RaceID != \'1046\'\nORDER BY r.fastestLapTime ASC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_6

RaceID  driverID    forename     surname fastestLapTime  \
0       1032       832      Carlos       Sainz        01:05.6   
1       1032       830         Max  Verstappen        01:06.1   
2       1060       830         Max  Verstappen        01:06.2   
3       1032         1       Lewis    Hamilton        01:06.7   
4        997         8        Kimi   Raikkonen        01:06.9   
...      ...       ...         ...         ...            ...   
7356     957       836      Pascal    Wehrlein        02:48.8   
7357      45         3        Nico     Rosberg        02:50.9   
7358     871       813      Pastor   Maldonado        02:56.1   
7359      45        26       Scott       Speed        03:01.9   
7360      45        24  Vitantonio      Liuzzi        03:22.3   

      fastestLapSpeed  circuitId        date                          name  
0             236.894         70  2020-07-12                 Red Bull Ring  
1             235.010         70  2020-07-12                 Red Bull Ring  
2             234.815         70  2021-07-04                 Red Bull Ring  
3             232.989         70  2020-07-12                 Red Bull Ring  
4             232.160         70  2018-07-01                 Red Bull Ring  
...               ...        ...         ...                           ...  
7356          125.634          9  2016-07-10           Silverstone Circuit  
7357          108.410         20  2007-07-22                   Nurburgring  
7358          143.116         13  2012-09-02  Circuit de Spa-Francorchamps  
7359          101.884         20  2007-07-22                   Nurburgring  
7360           91.610         20  2007-07-22                   Nurburgring  

[7361 rows x 9 columns]

The above query shows that the fastest ever racing lap was recorded by Carlos Sainz at Red Bull Ring (2020-07-12), with a time of 01:05.6. Next, we're going to look at the fastest laps ever recorded at each track:

In [9]:
df_7 = _deepnote_execute_sql('-- Fastest Lap by Track\n\nSELECT \n    c.name AS track,\n    MIN(r.fastestLapTime) AS fastest_lap\nFROM \'results.csv\' r\nJOIN \'races.csv\' ra ON r.RaceId = ra.RaceID\nJOIN \'drivers.csv\' d ON r.driverId = d.driverId\nLEFT JOIN \'circuits.csv\' c ON ra.circuitId = c.circuitId\nWHERE r.fastestLapTime <> \'0\' AND c.name IS NOT NULL AND r.RaceID != \'1046\'\nGROUP BY c.name\nORDER BY fastest_lap ASC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_7

track fastest_lap
0                          Red Bull Ring     01:05.6
1            Indianapolis Motor Speedway     01:10.3
2             Autodromo Jose Carlos Pace     01:10.5
3                 Circuit Park Zandvoort     01:11.0
4                      Circuit de Monaco     01:12.9
5              Circuit Gilles Villeneuve     01:13.0
6                         Hockenheimring     01:13.7
7          Circuit de Nevers Magny-Cours     01:15.3
8          Autodromo Enzo e Dino Ferrari     01:15.4
9         Circuit de Barcelona-Catalunya     01:15.6
10                           Hungaroring     01:16.6
11          Autodromo Hermanos Rodriguez     01:17.7
12                         Fuji Speedway     01:18.4
13    Autodromo Internacional do Algarve     01:18.7
14                   Silverstone Circuit     01:18.7
15  Autodromo Internazionale del Mugello     01:18.8
16        Albert Park Grand Prix Circuit     01:20.2
17          Autodromo Nazionale di Monza     01:21.0
18          Losail International Circuit     01:23.1
19                         Istanbul Park     01:24.7
20                    Yas Marina Circuit     01:26.1
21           Buddh International Circuit     01:27.2
22                           Nurburgring     01:28.1
23         Bahrain International Circuit     01:30.2
24               Jeddah Corniche Circuit     01:30.7
25                        Suzuka Circuit     01:30.9
26         Miami International Autodrome     01:31.3
27        Shanghai International Circuit     01:32.2
28                   Circuit Paul Ricard     01:32.7
29          Sepang International Circuit     01:34.0
30                        Sochi Autodrom     01:35.7
31               Circuit of the Americas     01:36.1
32               Valencia Street Circuit     01:38.6
33          Korean International Circuit     01:39.6
34             Marina Bay Street Circuit     01:41.9
35                     Baku City Circuit     01:43.0
36          Circuit de Spa-Francorchamps     01:45.1

Let's visualise these findings in a line chart, with lap times in ascending order:

In [10]:
DeepnoteChart(df_7, """{"layer":[{"layer":[{"mark":{"clip":true,"type":"trail","color":"#439894","tooltip":true},"encoding":{"x":{"sort":null,"type":"nominal","field":"track","scale":{"type":"linear","zero":false}},"y":{"sort":null,"type":"nominal","field":"fastest_lap","scale":{"type":"linear","zero":false}}}},{"mark":{"size":100,"type":"point","opacity":0,"tooltip":true},"encoding":{"x":{"sort":null,"type":"nominal","field":"track","scale":{"type":"linear","zero":false}},"y":{"sort":null,"type":"nominal","field":"fastest_lap","scale":{"type":"linear","zero":false}}}}]}],"title":"Fastest Laps By Track","config":{"legend":{}},"$schema":"https://vega.github.io/schema/vega-lite/v5.json","encoding":{}}""")

As previously discovered, the fastest ever lap was recorded at Red Bull Ring. The track with the slowest time is the iconic Circuit de Spa-Francorchamps in Belgium. 

## Driver Performance Analysis

Now we're going to dig deeper into driver performance analysis. Let's begin by finding the driver with the most career points:

In [11]:
df_14 = _deepnote_execute_sql('-- Find career points leader\n\nSELECT \n    r.driverId,\n    SUM(r.points) AS total_points,\n    d.forename,\n    d.surname\nFROM \'results.csv\' r\nJOIN \'drivers.csv\' d ON r.driverId = d.driverId\nGROUP BY r.driverId, d.forename, d.surname\nORDER BY total_points DESC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_14

driverID  total_points   forename     surname
0           1        4396.5      Lewis    Hamilton
1          20        3098.0  Sebastian      Vettel
2           4        2061.0   Fernando      Alonso
3         830        1983.5        Max  Verstappen
4           8        1873.0       Kimi   Raikkonen
..        ...           ...        ...         ...
850       677           0.0     Travis        Webb
851       683           0.0     Leslie      Thorne
852       772           0.0       Mack    Hellings
853       652           0.0        Ted   Whiteaway
854       730           0.0     George      Fonder

[855 rows x 4 columns]

The driver with the most career points is Lewis Hamilton, with 4396, followed by Sebastian Vettel with 3098. 

Next, identifying the driver with the highest average points per race:

In [12]:
df_8 = _deepnote_execute_sql('-- Find highest avg points per race\n\nSELECT \n    r.driverId,\n    AVG(r.points) AS average_points,\n    COUNT(r.RaceId) AS total_races,\n    d.surname,\n    d.forename\nFROM \'results.csv\' r\nJOIN \'drivers.csv\' d ON r.driverId = d.driverId\nGROUP BY r.driverId, d.surname, d.forename\nORDER BY average_points DESC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_8

driverID  average_points  total_races     surname   forename
0           1       14.182258          310    Hamilton      Lewis
1         830       12.168712          163  Verstappen        Max
2          20       10.326667          300      Vettel  Sebastian
3         822        8.845771          201      Bottas   Valtteri
4         844        8.262136          103     Leclerc    Charles
..        ...             ...          ...         ...        ...
850       301        0.000000            1      Morgan       Dave
851       545        0.000000            1      Gamble       Fred
852       652        0.000000            1   Whiteaway        Ted
853       683        0.000000            1      Thorne     Leslie
854       730        0.000000            3      Fonder     George

[855 rows x 5 columns]

Lewis Hamilton has the highest average points per race with 14.18, which comes as no surprise given his unprecedented success at the pinnacle of motor racing. He is followed by the Red Bull prodigy himself, Max Verstappen, with an average of 12.16.

Which driver has the highest average career finish? We will set a minimum threshold of 20 races to discount any outliers:

In [37]:
df_9 = _deepnote_execute_sql('-- Find the driver with the highest average career finish (min 20 races)\n\nSELECT \n    r.driverId,\n    AVG(NULLIF(CAST(r.position AS INT), 0)) AS average_position,\n    COUNT(r.RaceId) AS total_races,\n    d.surname,\n    d.forename\nFROM \'results.csv\' r\nJOIN \'drivers.csv\' d ON r.driverId = d.driverId\nGROUP BY r.driverId, d.surname, d.forename\nHAVING COUNT(r.RaceId) > 20\nORDER BY average_position ASC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_9

driverID  average_position  total_races      surname forename
0         647          2.181818           36       Ascari  Alberto
1         579          2.250000           58       Fangio     Juan
2         642          2.814815           37       Farina     Nino
3         328          2.952381          100      Stewart   Jackie
4         117          2.958042          202        Prost    Alain
..        ...               ...          ...          ...      ...
250        39         17.181818           48  Karthikeyan   Narain
251       819         17.300000           39          Pic  Charles
252       820         17.343750           35      Chilton      Max
253        29         17.428571           21     Yamamoto    Sakon
254       853         17.812500           22      Mazepin   Nikita

[255 rows x 5 columns]

In [24]:
DeepnoteChart(df_9, """{"layer":[{"layer":[{"mark":{"clip":true,"type":"bar","tooltip":true},"encoding":{"x":{"sort":null,"type":"nominal","field":"surname","scale":{"type":"linear"}},"y":{"sort":null,"type":"quantitative","field":"average_position","scale":{"type":"linear"},"format":{"type":"default","decimals":0},"formatType":"numberFormatFromNumberType"},"color":{"sort":null,"type":"quantitative","field":"average_position","scale":{"scheme":"purples"},"aggregate":"sum"}}}]}],"title":"Avg Career Finish Position (Top 20)","config":{"legend":{}},"$schema":"https://vega.github.io/schema/vega-lite/v5.json","encoding":{}}""")

Next, the drivers with the lowest average career finish:

In [120]:
df_10 = _deepnote_execute_sql('-- Find the driver with the lowest average career finish (min 20 races)\n\nSELECT \n    r.driverId,\n    AVG(NULLIF(CAST(r.position AS INT), 0)) AS average_position,\n    COUNT(r.RaceId) AS total_races,\n    d.surname,\n    d.forename\nFROM \'results.csv\' r\nJOIN \'drivers.csv\' d ON r.driverId = d.driverId\nGROUP BY r.driverId, d.surname, d.forename\nHAVING COUNT(r.RaceId) > 20\nORDER BY average_position DESC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_10

driverID  average_position  total_races      surname forename
0         853         17.812500           22      Mazepin   Nikita
1          29         17.428571           21     Yamamoto    Sakon
2         820         17.343750           35      Chilton      Max
3         819         17.300000           39          Pic  Charles
4          39         17.181818           48  Karthikeyan   Narain
..        ...               ...          ...          ...      ...
250       117          2.958042          202        Prost    Alain
251       328          2.952381          100      Stewart   Jackie
252       642          2.814815           37       Farina     Nino
253       579          2.250000           58       Fangio     Juan
254       647          2.181818           36       Ascari  Alberto

[255 rows x 5 columns]

The data shows us that the driver with the lowest average finishing position with a minimum of 20 career races is Nikita Mazepin, with an average of 17.8, followed by Sakon Yamamoto with 17.4. See below for visualisation:

In [25]:
DeepnoteChart(df_10, """{"layer":[{"layer":[{"mark":{"clip":true,"type":"bar","tooltip":true},"encoding":{"x":{"sort":null,"type":"nominal","field":"surname","scale":{"type":"linear"}},"y":{"sort":null,"type":"quantitative","field":"average_position","scale":{"type":"linear"},"format":{"type":"default","decimals":null},"aggregate":"sum","formatType":"numberFormatFromNumberType"},"color":{"sort":null,"type":"quantitative","field":"average_position","scale":{"scheme":"purples"},"aggregate":"sum"}}}]}],"title":"Avg Career Finish Position (Bottom 20)","config":{"legend":{}},"$schema":"https://vega.github.io/schema/vega-lite/v5.json","encoding":{}}""")

The next SQL query is designed to analyse Formula 1 drivers' performance based on their career points achieved, with a minimum threshold of 20 races. It categorises drivers into four performance quartiles, assigning an experience level based on the number of races they have competed in. Additionally, it calculates the average career points across all drivers to be used as a reference point.

Subquery (QuartileData): The inner query selects driver details, calculates total career points, and assigns an experience level based on the number of races participated in. It filters out drivers with less than 20 career points.

Experience Level Assignment: Based on the number of races a driver has participated in, they are categorised into one of four experience levels: '1-50 races', '51-100 races', '101-150 races', or '151+ races'.

Performance Quartile Calculation: Using the NTILE window function, drivers are divided into four performance quartiles based on their total career points, with the first quartile representing the top performers.

Average Career Points Calculation: The query calculates the average career points across all drivers using the AVG window function.

Final Selection: The outer query selects the driver's ID, surname, forename, total career points, experience level, performance quartile, and average career points across all drivers.

Ordering: Finally, the results are ordered in descending order based on total career points, showcasing the drivers with the highest points at the top.

In [17]:
df_16 = _deepnote_execute_sql('-- Divide drivers into quartiles based on avg career points (min 20 races)\n\nSELECT \n    driverId, \n    surname, \n    forename, \n    total_points,\n    experience_level,\n    NTILE(4) OVER (ORDER BY total_points DESC) AS performance_quartile,\n    AVG(total_points) OVER () AS avg_career_points\nFROM (\n    SELECT \n        r.driverId, \n        d.surname, \n        d.forename, \n        SUM(r.points) AS total_points,\n        CASE\n            WHEN COUNT(r.RaceId) <= 50 THEN \'1-50 races\'\n            WHEN COUNT(r.RaceId) <= 100 THEN \'51-100 races\'\n            WHEN COUNT(r.RaceId) <= 150 THEN \'101-150 races\'\n            ELSE \'151+ races\'\n        END as experience_level\n    FROM \'results.csv\' r\n    JOIN \'drivers.csv\' d ON r.driverId = d.driverId\n    GROUP BY r.driverId, d.surname, d.forename\n    HAVING SUM(r.points) > 20\n) AS QuartileData\nORDER BY total_points DESC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_16

driverID     surname     forename  total_points experience_level  \
0           1    Hamilton        Lewis        4396.5       151+ races   
1          20      Vettel    Sebastian        3098.0       151+ races   
2           4      Alonso     Fernando        2061.0       151+ races   
3         830  Verstappen          Max        1983.5       151+ races   
4           8   Raikkonen         Kimi        1873.0       151+ races   
..        ...         ...          ...           ...              ...   
139       838   Vandoorne      Stoffel          26.0       1-50 races   
140       170        Fabi          Teo          23.0     51-100 races   
141       219   Jabouille  Jean-Pierre          21.0     51-100 races   
142       841  Giovinazzi      Antonio          21.0     51-100 races   
143       418     Gregory       Masten          21.0       1-50 races   

     performance_quartile  avg_career_points  
0                       1         327.000556  
1                       1         327.000556  
2                       1         327.000556  
3                       1         327.000556  
4                       1         327.000556  
..                    ...                ...  
139                     4         327.000556  
140                     4         327.000556  
141                     4         327.000556  
142                     4         327.000556  
143                     4         327.000556  

[144 rows x 7 columns]

In [119]:
DeepnoteChart(df_16, """{"layer":[{"layer":[{"mark":{"clip":true,"type":"bar","tooltip":true},"encoding":{"x":{"sort":{"order":"descending","encoding":"y"},"type":"nominal","field":"experience_level","scale":{"type":"linear"}},"y":{"sort":null,"type":"quantitative","field":"total_points","scale":{"type":"linear"},"format":{"type":"default","decimals":2},"aggregate":"average","formatType":"numberFormatFromNumberType"},"color":{"sort":null,"type":"quantitative","field":"total_points","scale":{"scheme":"oranges"},"aggregate":"average"}}}]}],"title":"Experience vs Avg Career Points","config":{"legend":{}},"$schema":"https://vega.github.io/schema/vega-lite/v5.json","encoding":{}}""")

As expected, more races drastically increases the average of a driver's total career points. But what effect does experience level have on other performance metrics?

Next, we will examine Formula 1 drivers based on their average career finish positions, using the same format and criteria as above:

In [65]:
df_15 = _deepnote_execute_sql('-- Divide drivers into quartiles based on avg career finish position (min 20 races)\n\nSELECT \n    driverId, \n    surname, \n    forename, \n    average_position, \n    total_races,\n    experience_level,\n    NTILE(4) OVER (PARTITION BY experience_level ORDER BY average_position) AS performance_quartile,\n    AVG(average_position) OVER (PARTITION BY experience_level) AS avg_career_finish_position\nFROM (\n    SELECT \n        r.driverId,\n        d.surname,\n        d.forename,\n        AVG(NULLIF(CAST(r.position AS SIGNED), 0)) AS average_position,\n        COUNT(r.RaceId) AS total_races,\n        CASE\n            WHEN COUNT(r.RaceId) <= 50 THEN \'1-50 races\'\n            WHEN COUNT(r.RaceId) <= 100 THEN \'51-100 races\'\n            WHEN COUNT(r.RaceId) <= 150 THEN \'101-150 races\'\n            ELSE \'151+ races\'\n        END as experience_level\n    FROM \'results.csv\' r\n    JOIN \'drivers.csv\' d ON r.driverId = d.driverId\n    WHERE r.position <> \'0\'\n    GROUP BY r.driverId, d.surname, d.forename\n    HAVING total_races > 20\n) AS QuartileData\nORDER BY experience_level, average_position ASC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_15

driverID     surname    forename  average_position  total_races  \
0         647      Ascari     Alberto          2.181818           22   
1         579      Fangio        Juan          2.250000           44   
2         642      Farina        Nino          2.814815           27   
3         475        Moss    Stirling          3.459459           37   
4         578    Hawthorn        Mike          3.696970           33   
..        ...         ...         ...               ...          ...   
171       841  Giovinazzi     Antonio         13.392857           56   
172        10       Glock        Timo         13.770270           74   
173        24      Liuzzi  Vitantonio         13.818182           55   
174       828    Ericsson      Marcus         13.918919           74   
175       849      Latifi    Nicholas         15.431373           51   

    experience_level  performance_quartile  avg_career_finish_position  
0         1-50 races                     1                    9.065964  
1         1-50 races                     1                    9.065964  
2         1-50 races                     1                    9.065964  
3         1-50 races                     1                    9.065964  
4         1-50 races                     1                    9.065964  
..               ...                   ...                         ...  
171     51-100 races                     4                    7.994796  
172     51-100 races                     4                    7.994796  
173     51-100 races                     4                    7.994796  
174     51-100 races                     4                    7.994796  
175     51-100 races                     4                    7.994796  

[176 rows x 8 columns]

For our final driver performance chart, let's examine the effect of experience on average finish position:

In [118]:
DeepnoteChart(df_15, """{"layer":[{"layer":[{"mark":{"clip":true,"type":"bar","tooltip":true},"encoding":{"x":{"sort":{"order":"descending","encoding":"y"},"type":"nominal","field":"experience_level","scale":{"type":"linear"}},"y":{"sort":null,"type":"quantitative","field":"average_position","scale":{"type":"linear"},"format":{"type":"default","decimals":null},"formatType":"numberFormatFromNumberType"},"color":{"sort":null,"type":"quantitative","field":"avg_career_finish_position","scale":{"scheme":"oranges"},"aggregate":"average"}}}]}],"title":"Experience vs Avg Finish Position","config":{"legend":{}},"$schema":"https://vega.github.io/schema/vega-lite/v5.json","encoding":{}}""")

The data shows that drivers with more experience have a higher average career finishing position. This is logical as drivers performing poorly won't get the opportunity to keep their seat for long, thus not allowing them to participate in a high number of races. Formula 1 teams are notoriously ruthless with who they employ, and there is always a plethora of driving talent waiting for their opportunity. 

## Constructor Performance Analysis

To wrap things up, we're going to briefly examine constructor performance. 

In [40]:
df_12 = _deepnote_execute_sql('-- Find the constructor with the highest average finish (min 20 races)\n\nSELECT \n    r.constructorId,\n    AVG(NULLIF(CAST(r.position AS INT), 0)) AS average_position,\n    COUNT(r.RaceId) AS total_races,\nFROM \'results.csv\' r\nJOIN \'constructor_results.csv\' cr ON r.constructorId = cr.constructorId\nGROUP BY r.constructorId\nHAVING COUNT(r.RaceId) > 20\nORDER BY average_position ASC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_12

constructorId  average_position  total_races
0              196          3.655172          920
1              191          3.871795         2541
2               23          4.062500          578
3              131          4.153226       145040
4              118          4.185185          781
..             ...               ...          ...
121             47               NaN          196
122             60               NaN          992
123             74               NaN           64
124             85               NaN           36
125             86               NaN          196

[126 rows x 3 columns]

The data shows that Constructor ID #196 has highest average career finish at 3.65, followed by Constructor ID #191 at 3.87.

In [41]:
df_13 = _deepnote_execute_sql('-- Find the constructor with the lowest average finish (min 20 races)\n\nSELECT \n    r.constructorId,\n    AVG(NULLIF(CAST(r.position AS INT), 0)) AS average_position,\n    COUNT(r.RaceId) AS total_races,\nFROM \'results.csv\' r\nJOIN \'constructor_results.csv\' cr ON r.constructorId = cr.constructorId\nGROUP BY r.constructorId\nHAVING COUNT(r.RaceId) > 20\nORDER BY average_position DESC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_13

constructorId  average_position  total_races
0              164         18.987342         6612
1              166         17.877551         2888
2              206         17.191489         6431
3              207         16.670455         6272
4              205         16.377358         2888
..             ...               ...          ...
121             47               NaN          196
122             60               NaN          992
123             74               NaN           64
124             85               NaN           36
125             86               NaN          196

[126 rows x 3 columns]

Constructor ID #164 has lowest average career finish at 18.98, followed by Constructor ID #166 at 3.87.

# Insights & Conclusion

## Recap

Let's recap our findings of the F1 analysis from 1953-2020:

- Most races: Fernando Alonso (358)

- Most career points: Lewis Hamilton

- Fastest ever lap: Carlos Sainz (Red Bull Ring, 07-12-2020) 

- Highest average driver finish position (min 20 races): Alberto Ascari (1.33)

- Lowest average driver finish position (min 20 races): Max Chilton (15.8)

- Highest average constructor finish position (min 20 races): Constructor #106

- Lowest average constructor finish position (min 20 races): Constructor #206

## Who is the Greatest Driver of All Time?

Determining an answer to this question in an objective manner is, realistically, a near impossible task. As fans of the sport will naturally understand, there are simply too many variables at play to be able to accurately conclude a definitive list through statistics alone. 

The Formula 1 points system has undergone numerous changes over the years, evolving to adapt to the sport's shifting dynamics and competitive landscape. These alterations in the distribution of points have significant implications when attempting to compare drivers across different eras. 

In earlier years, only a handful of top finishers were awarded points, whereas in more recent formats, points are distributed more broadly down the grid. This means that drivers in the modern era have the potential to accumulate points more consistently, even if they are not consistently finishing in the top positions. 

Additionally, advancements in technology have dramatically transformed Formula 1 cars, making them faster, safer, and more reliable. These technological improvements, coupled with changes in regulations and car design, have resulted in substantial disparities in car performance across different periods. 

As a result, comparing drivers solely based on their points tally or race finishes can be misleading, as it does not account for the varying levels of competition, car performance, and points distribution systems in place at different times. Therefore, while statistics provide valuable insights, they may not fully capture a driver's skill, impact, or the context of their achievements, making it challenging to definitively conclude who the better drivers are across different Formula 1 eras.

It's also equally critical to consider which constructors the drivers are representing. The disparity in Formula 1 team budgets plays a pivotal role in influencing driver performance, creating a significant divide between the teams at the top and those further down the grid. Teams with larger budgets, often backed by major automotive manufacturers or wealthy entities, have the financial resources to invest in cutting-edge technology, top-tier engineering talent, and extensive research and development. 

This investment translates into faster, more reliable cars, providing their drivers with a competitive advantage on the track. In contrast, teams with smaller budgets face limitations in their ability to develop and maintain high-performance vehicles, often resulting in less competitive machinery. This budgetary constraint can hinder a driver's ability to consistently compete at the front of the grid, regardless of their individual skill and talent. 

Additionally, well-funded teams can offer more comprehensive support, including advanced simulation tools, extensive data analysis, and superior pit strategy, all of which contribute to optimising a driver's performance. Consequently, while driver skill is undeniably a crucial factor in Formula 1 success, the financial capabilities of their team play a substantial role in determining the extent to which a driver can realize their potential and achieve top results.

## Conclusion

This Formula 1 Data Analysis project has helped us breakdown the intricate dynamics of Formula 1 racing, providing valuable insights into driver performance and statistics. The robust capabilities of SQL allowed us to delve deep into data manipulation, uncovering patterns, trends, and performance metrics that shed light on the iconic drivers, teams, and circuits that have defined the sport for decades.

The integration of data visualisations via Deepnote and Tableau brought our findings to life, transforming complex datasets into interactive and engaging charts. This makes the data more accessible, allowing enthusiasts and analysts alike to interact with the data in a meaningful way. 

We have also established that while statistics provide valuable insights, they may not fully capture a driver's skill, impact, or the context of their achievements, making it challenging to definitively conclude who the better drivers are across different Formula 1 eras. Through this performance analysis and comprehensive reporting, we have provided a data-driven lens through which the world of Formula 1 can be understood and appreciated with a unique and insightful perspective.

Thank you for reading! Who gets your vote for greatest driver of all time?

In [26]:
BestDriverEver = 'Jackie Stewart'

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=82671792-e81f-4713-96aa-a93ee5b52bd4' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>